[package]
name = "bitvmx-client"
version = "0.8.4"
edition = "2021"

[dependencies]
sha2 = "0.11"
anyhow = "1.0.104"
bitcoin = { version = "0.32.102", features = ["std", "rand-std"] }
clap = { version = "4.6.6", features = ["derive"] }
config = "0.15.11"
console = "0.16.4"
hex = "0.4.3"
lazy_static = "1.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.1", features = ["v4", "v5"] }
chrono = "0.4.45"
tokio = { version = "1.40.0", features = ["sync"] }
signature = "2.2"
rsa = "0.9"
enum_dispatch = { version = "0.3.13" }
ctrlc = "3.5.2"

bitcoincore-rpc = { version = "0.19.0" }
bitcoin-script = { git = "https://github.com/FairgateLabs/rust-bitcoin-script/", tag = "v0.6.0" }
bitcoin-scriptexec = { git = "https://github.com/FairgateLabs/rust-bitcoin-scriptexec/", tag = "v0.6.0" }

bitvmx-key-manager = { git = "https://github.com/FairgateLabs/rust-bitvmx-key-manager.git", tag = "v0.8.4" }
bitvmx-protocol-builder = { git = "https://github.com/FairgateLabs/rust-bitvmx-protocol-builder.git", tag = "v0.8.4" }
bitcoin-coordinator = { git = "https://github.com/FairgateLabs/rust-bitvmx-bitcoin", tag = "v0.8.4" }
rust-bitvmx-storage-backend = { git = "https://github.com/FairgateLabs/rust-bitvmx-storage-backend.git", tag = "v0.8.4" }
bitvmx-settings = { git = "https://github.com/FairgateLabs/rust-bitvmx-settings.git", tag = "v0.8.4" }
bitvmx-bitcoin-rpc = { git = "https://github.com/FairgateLabs/rust-bitvmx-bitcoin-rpc.git", tag = "v0.8.4" }
bitvmx-broker = { git = "https://github.com/FairgateLabs/rust-bitvmx-broker.git", tag = "v0.8.4" }
emulator = { git = "https://github.com/FairgateLabs/BitVMX-CPU", tag = "v0.8.4" }
bitcoin-script-riscv = { git = "https://github.com/FairgateLabs/BitVMX-CPU", tag = "v0.8.4" }
bitvmx-cpu-definitions = { git = "https://github.com/FairgateLabs/BitVMX-CPU", tag = "v0.8.4" }
bitcoin-script-stack = { git = "https://github.com/FairgateLabs/rust-bitcoin-script-stack", tag = "v0.6.0" }
bitcoin-script-functions = { git = "https://github.com/FairgateLabs/rust-bitcoin-script-functions", tag = "v0.6.0" }

bitvmx-wallet = { git = "https://github.com/FairgateLabs/rust-bitvmx-wallet.git", tag = "v0.8.4" }
bitvmx-job-dispatcher-types = { git = "https://github.com/FairgateLabs/rust-bitvmx-job-dispatcher", features = [
    "emulator",
    "prover",
    "garbled",
], tag = "v0.8.4" }
bitvmx-job-dispatcher = { git = "https://github.com/FairgateLabs/rust-bitvmx-job-dispatcher", tag = "v0.8.4" }
bitvmx-dispatcher-utils = { git = "https://github.com/FairgateLabs/rust-bitvmx-job-dispatcher", tag = "v0.8.4" }
redact = { version = "0.1", features = ["serde", "zeroize"] }
time = "0.3.55"


[dev-dependencies]
futures-util = "0.3"
criterion = { version = "0.8.2", features = ["html_reports"] }
bitcoind = { git = "https://github.com/FairgateLabs/rust-bitcoind.git", tag = "v0.8.4" }
reqwest = "0.13.4"

zk-result = { git = "https://github.com/FairgateLabs/rust-bitvmx-zk-proof.git", tag = "v0.8.4" }
[features]
default = ["cardinal", "union"]
cardinal = []
union = []
testpanic = []

[profile.release-with-debug]
inherits = "release"
debug = true

[[example]]
name = "union"
path = "examples/union/main.rs"
required-features = ["union"]

[[example]]
name = "cardinal"
path = "examples/cardinal/main.rs"
required-features = ["cardinal"]

[[bench]]
name = "message_queue"
harness = false
