bitcoin:
  network: bitcoin
  url: "https://frosty-winter-sailboat.btc.quiknode.pro/6b2662d80a2edeeaac3b871c546c15ccabf5fe3a/"
  # url: [testnet] "https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/"
  username: ""
  password: ""
  wallet: test_wallet

builder:
  protocol_amount: 2450000
  speedup_amount: 2450000
  locked_amount: 95000000
  locked_blocks: 200
  ecdsa_sighash_type: SIGHASH_ALL
  taproot_sighash_type: SIGHASH_ALL

key_manager:
  network: bitcoin
  key_derivation_path: m/101/1/0/0/
  key_derivation_seed: 1111beefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef
  winternitz_seed: 1111beefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef

key_storage:
  password: secret_password_2
  path: /tmp/op_1/keys.db

storage:
  db: /tmp/op_1/storage.db
  program: /tmp/op_1/

p2p:
  address: /ip4/127.0.0.1/tcp/61180
  key: 080112408888ee9eac838c47e3a17f354f30477357a7f6b63a6ceabe70f821ae76bcd461f87ef7c8f92b9486d8c82e25738cdf643311c700e25e0d105eff81b497f5abeb
  peer_id_file: peer_id
  timeout: 5

monitor:
  checkpoint_height: 896583
  confirmation_threshold: 6

broker_storage: /tmp/op_1/broker.db
broker_port: 22222

client:
  # Number of retries for requests
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000
