bitcoin:
  network: testnet
  url: https://floral-empty-tree.btc-testnet.quiknode.pro/56ae97aeb4da9032b9f34e2730bc6d9e70bc7d63/
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: secret_password_4
  path: /tmp/op_3/keys.db
storage:
  path: /tmp/op_3/storage.db
p2p:
  address: 127.0.0.1:61182
  priv_key: config/keys/op_3.key
  timeout: 5
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4631677
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 44444
  ip: 127.0.0.1
  id: 0
  priv_key: ../rust-bitvmx-broker/certs/services.key
  storage: 
    path: /tmp/op_3/broker.db
components:
  l2:
    address: 127.0.0.1:7000
    priv_key: config/keys/l2.key
    id: 2
  bitvmx:
    address: 127.0.0.1:7000
    priv_key: config/keys/bitvmx.key
    id: 2
  emulator:
    address: 127.0.0.1:7000
    priv_key: config/keys/emulator.key
    id: 2
  prover:
    address: 127.0.0.1:7000
    priv_key: config/keys/prover.key
    id: 2
client:
  retry: 1
  retry_delay: 1000
