bitcoin:
  network: testnet
  url: "https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/"
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: secret_password_5
  path: /tmp/op_4/keys.db

storage:
  path: /tmp/op_4/storage.db

p2p:
  address: /ip4/127.0.0.1/tcp/61183
  key: config/keys/op_4.key
  peer_id_file: peer_id
  timeout: 5

coordinator_settings:
  max_unconfirmed_speedups: 10
  max_tx_weight: 400000
  max_rbf_attempts: 10
  min_funding_amount_sats: 10000
  rbf_fee_percentage: 1.5
  max_feerate_sat_vb: 1000
  min_blocks_before_resend_speedup: 1
  monitor_settings:
    max_monitoring_confirmations: 100
    confirmation_threshold: 2
    indexer_settings:
      checkpoint_height: 4626057

coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 10

broker_storage:
  path: /tmp/op_4/broker.db
broker_port: 55554

client:
  # Number of retries for requests
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000