bitcoin:
  network: testnet
  url: https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: secret_password_3
  path: /tmp/op_2/keys.db
storage:
  path: /tmp/op_2/storage.db
p2p:
  address: 127.0.0.1:61181
  key: config/keys/op_2.key
  timeout: 5
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4631677
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 33333
  ip: 127.0.0.1
  id: 0
  priv_key: ../rust-bitvmx-broker/certs/services.key
  storage: 
    path: /tmp/op_2/broker.db
components:
  l2:
    address: 127.0.0.1:7000
    priv_key: config/keys/l2.key
    id: 1
  bitvmx:
    address: 127.0.0.1:7000
    priv_key: config/keys/bitvmx.key
    id: 1
  emulator:
    address: 127.0.0.1:7000
    priv_key: config/keys/emulator.key
    id: 1
  prover:
    address: 127.0.0.1:7000
    priv_key: config/keys/prover.key
    id: 1
client:
  retry: 1
  retry_delay: 1000
