bitcoin:
  network: testnet
  url: "https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/"
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: secret_password_2
  path: /tmp/op_1/keys.db

storage:
  path: /tmp/op_1/storage.db

p2p:
  address: /ip4/127.0.0.1/tcp/61180
  key: 080112408888ee9eac838c47e3a17f354f30477357a7f6b63a6ceabe70f821ae76bcd461f87ef7c8f92b9486d8c82e25738cdf643311c700e25e0d105eff81b497f5abeb
  peer_id_file: peer_id
  timeout: 5

coordinator_settings:
  monitor_settings:
    confirmation_threshold: 1
    indexer_settings:
      checkpoint_height: 4400538

coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 10

broker_storage:
  path: /tmp/op_1/broker.db
broker_port: 22222

client:
  # Number of retries for requests
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000
