bitcoin:
  network: testnet
  url: "https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/"
  username: ""
  password: ""
  wallet: test_wallet

key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/

key_storage:
  password: secret_password_3
  path: /tmp/op_2/keys.db

storage:
  path: /tmp/op_2/storage.db

p2p:
  address: /ip4/127.0.0.1/tcp/61181
  key: config/keys/op_2.key
  peer_id_file: peer_id
  timeout: 5

coordinator_settings:
  max_unconfirmed_speedups: 5
  max_tx_weight: 4000000
  max_rbf_attempts: 5
  min_funding_amount_sats: 1000
  rbf_fee_percentage: 1.5
  max_feerate_sat_vb: 6
  min_blocks_before_resend_speedup: 1
  base_fee_multiplier: 1.0
  bump_fee_percentage: 1.5
  monitor_settings:
    confirmation_threshold: 6
    max_monitoring_confirmations: 100
    indexer_settings:
      checkpoint_height: 4631118
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1

broker_storage:
  path: /tmp/op_2/broker.db
broker_port: 33333

client:
  # Number of retries for requests
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000