bitcoin:
  network: testnet
  url: https://floral-empty-tree.btc-testnet.quiknode.pro/56ae97aeb4da9032b9f34e2730bc6d9e70bc7d63/
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: secret_password_5
  path: /tmp/op_4/keys.db
storage:
  path: /tmp/op_4/storage.db
comms:
  address: 127.0.0.1:61183
  priv_key: config/keys/op_4.key
  storage_path: /tmp/op_4/comms.db
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4631677
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 55554
  ip: 127.0.0.1
  priv_key: config/keys/services.key
  storage: 
    path: /tmp/op_4/broker.db
components:
  l2:
    priv_key: config/keys/l2.key
    id: 0
  bitvmx:
    priv_key: config/keys/bitvmx.key
    id: 0
  emulator:
    priv_key: config/keys/emulator.key
    id: 0
  prover:
    priv_key: config/keys/prover.key
    id: 0
client:
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000

wallet:
  db_path: /tmp/testnet/op_4/wallet.db
  start_height: 4631993
