bitcoin:
  network: testnet
  url: https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: secret_password_2
  path: /tmp/op_1/keys.db
storage:
  path: /tmp/op_1/storage.db
p2p:
  address: /ip4/127.0.0.1/tcp/61180
  key: config/keys/op_1.key
  peer_id_file: peer_id
  timeout: 5
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4631677
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker_storage:
  path: /tmp/op_1/broker.db
broker_port: 22222
client:
  retry: 1
  retry_delay: 1000
