bitcoin:
  network: testnet
  url: https://distinguished-intensive-frost.btc-testnet.quiknode.pro/38d0f064dc8e72fe44d8a9a762d448bc64c54619/
  username: ''
  password: ''
  wallet: test_wallet
key_manager:
  network: testnet
  key_derivation_path: m/101/1/0/0/
key_storage:
  password: secret_password_3
  path: /tmp/op_2/keys.db
storage:
  path: /tmp/op_2/storage.db
comms:
  address: 127.0.0.1:61181
  priv_key: config/keys/op_2.key
  storage_path: /tmp/op_2/comms.db
coordinator_settings:
  max_feerate_sat_vb: 2
  monitor_settings:
    indexer_settings:
      checkpoint_height: 4631677
coordinator:
  throtthle_bitcoin_updates_until_sync: 1
  throtthle_bitcoin_updates: 1
broker:
  allow_list: config/allow_list.yaml
  routing_table: config/routing_table.yaml
  port: 33333
  ip: 127.0.0.1
  priv_key: config/keys/services.key
  storage: 
    path: /tmp/op_2/broker.db
components:
  l2:
    ip: 127.0.0.1
    priv_key: config/keys/l2.key
    id: 0
  bitvmx:
    ip: 127.0.0.1
    priv_key: config/keys/bitvmx.key
    id: 0
  emulator:
    ip: 127.0.0.1
    priv_key: config/keys/emulator.key
    id: 0
  prover:
    ip: 127.0.0.1
    priv_key: config/keys/prover.key
    id: 0
client:
  retry: 1
  # Delay between retries in milliseconds
  retry_delay: 1000

wallet:
  db_path: /tmp/testnet/op_2/wallet.db
  start_height: 4631993
